name: Deploy to Github Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup NodeJS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - name: NPM Install
        run: |
          npm ci
      - name: Snowpack build
        env:
          SOURCE_URL: ${{github.server_url}}/${{github.repository}}
        run: |
          npm run build
          touch build/.nojekyll
          cp ./LICENSE ./build
          sed -i "s/UPSTREAM/$(echo $SOURCE_URL | sed 's/\//\\\//g')/" build/index.html
      - name: Push git subdirectory as branch
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}